version: 2
general:

jobs:
  build:
    branches:
      only:
        - site
    docker:
      - image: juristr/hugo-docker
    steps:
      - checkout
      - run: 
          name: "Install container dependencies for deploy"
          command: apk --no-cache add git openssh
      - run: 
          name: "Install node modules"
          command: npm install
      - run: 
          name: "Build and deploy to GitHub"
          command: npm run deploy